//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_ws.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vendingapi.lpwan.sgrid/", ConfigurationName="ServiceReference1.Transaction")]
    public interface Transaction {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vendingapi.lpwan.sgrid/Transaction/setTokenRequest", ReplyAction="http://vendingapi.lpwan.sgrid/Transaction/setTokenResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string setToken(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransactionChannel : test_ws.ServiceReference1.Transaction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionClient : System.ServiceModel.ClientBase<test_ws.ServiceReference1.Transaction>, test_ws.ServiceReference1.Transaction {
        
        public TransactionClient() {
        }
        
        public TransactionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string setToken(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6) {
            return base.Channel.setToken(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
        }
    }
}
